name = "costing-calculator"
compatibility_date = "2025-02-11"

pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "costingcalculator"
database_id = "aea99c46-60ae-4685-a03c-a88feb063566"
