name = "costing-calculator"
compatibility_date = "2025-02-11"

# Ensure Cloudflare Pages serves from /public directory
[site]
bucket = "./public"
entry-point = "public"

[[d1_databases]]
binding = "DB"
database_name = "costingcalculator"
database_id = "aea99c46-60ae-4685-a03c-a88feb063566"
