name: Move Frontend Files

on:
  push:
    branches:
      - main

jobs:
  move_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Move frontend files to public directory
        run: |
          mkdir -p public
          mv index.html public/ || echo "index.html not found"
          mv styles.css public/ || echo "styles.css not found"
          mv script.js public/ || echo "script.js not found"

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Moved frontend files to public directory" || echo "No changes to commit"
          git push
